config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'privacy', to: "toppages#privacy"
  get 'protocol', to: "toppages#protocol"
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :posts, only: [:new, :create, :edit, :show, :update, :destroy] do 
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :introduce, length: { maximum: 255 }
  validates_acceptance_of :agreement, allow_nil: false, on: :create
  
  has_secure_password
  
  has_many :posts, dependent: :destroy
  has_many :relationships,dependent: :destroy
  has_many :followings, through: :relationships, source: :follow,dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id',dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user,dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :fav_posts ,through: :favorites ,source: :post,dependent: :destroy
  
  has_many :comments, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids + [self.id])
  end
  
  def favorite(fav_post)
      self.favorites.find_or_create_by(post_id: fav_post.id)
  end  
    
  def unfavorite(fav_post)
    favorite = self.favorites.find_by(post_id: fav_post.id)
    favorite.destroy if favorite
  end
        
  def favorite?(fav_post)
    self.fav_posts.include?(fav_post)
  end
  
  mount_uploader :image, ImageUploader
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :destroy, :followings, :followers]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を編集しました。'
      render :edit
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end   
  end

  def destroy
    @user = User.find_by(id: params[:id])
    return redirect_to :root if @user.nil?
    
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @favorites = @user.fav_posts.page(params[:page])
    counts(@user)
  end

  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce, :age, :sex, :agreement, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  #def gravatar_url(user, options = { size: 80 })
    #gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #size = options[:size]
    #"https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  #end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled ">
    <% users.each do |user| %>
      <li class="media pb-4">
        <div class="rounded-circle">
          <% if user.image? %>
            <%= image_tag user.image.thumb130.url %>
          <% else %>
            <%= image_tag "/assets/icon.jpg", :size => '130x130' %>
          <% end %>
        </div>
        <div class="media-body pl-3">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="text-center">
  <h1 class="pt-4"><%= @user.name %>さんのアカウント編集</h1>
</div>
<div class="container">
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
      <% if @user.image? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg" %>
      <% end %>
      <%= f.file_field :image %>
      </div>
      
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      
      <div class="form-group">
        <%= f.label :age, '年齢', class:'control-label' %>
        <%= f.select :age, [["",""], ["10代","10"], ["20代","20"], ["30代","30"], ["40代","40"], ["50代","50"], ["60代","60"], ["70代以上","70"] ], {}, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :sex, '性別', class:'control-label' %>
        <%= f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {},   class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduce, '自己紹介（255文字未満）' %>
        <%= f.text_area :introduce, :maxlength => "255", :size => "80x5",  class: 'form-control'  %>
      </div>


      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（もう1度入力してください）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '更新', class: 'mb-3 btn btn-primary btn-block '  %>
    <% end %>
  </div>
</div>  
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row pt-3">
    <aside class="col-lg-4">
      <% if @user.image? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg" %>
      <% end %>
    
    </aside>
  <div class="col-lg-8 ">
    <h3><%= @user.name %></h3>
    <h6>性別：<%= @user.sex %></h6>
    <h6>年齢：<%= @user.age %>代</h6>
    <h6>自己紹介</h6>
        <p><%= @user.introduce %></p>
  </div>
  <div class= "col-md-2 offset-md-5">
      <span><%= render 'relationships/follow_button', user: @user %></span>
  </div>
</div>


<div class= "container">
  <div class="row pt-3">
    <div class="col-sm-12">
        <ul class="nav nav-tabs nav-justified mb-4">
          <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">IDEAS <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link  <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
        </ul>
    <%= render 'users', users: @followers %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container">
  <div class="row pt-3">
    <aside class="col-lg-4">
      <% if @user.image? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg" %>
      <% end %>
    </aside>
  <div class="col-lg-8 ">
    <h3><%= @user.name %></h3>
    <h6>性別：<%= @user.sex %></h6>
    <h6>年齢：<%= @user.age %>代</h6>
    <h6>自己紹介</h6>
        <p><%= @user.introduce %></p>
    
  </div>
  <div class= "col-md-2 offset-md-5">
      <span><%= render 'relationships/follow_button', user: @user %></span>
  </div>
</div>


<div class= "container">
  <div class="row pt-3">
    <div class="col-sm-12">
        <ul class="nav nav-tabs nav-justified mb-4">
          <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">IDEAS <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link  <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
        </ul>
    <%= render 'users', users: @followings %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container pl-5 pt-3">
  <%= render 'users', users: @users %>
</div>

app/views/users/likes.html.erb
<div class="container">
  <div class="row pt-3">
    <aside class="col-md-4">
      <% if @user.image? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg" %>
      <% end %>
    </aside>
  <div class="col-lg-8 ">
    <h3><%= @user.name %></h3>
    <h6>性別：<%= @user.sex %></h6>
    <h6>年齢：<%= @user.age %>代</h6>
    <h6>自己紹介</h6>
      <p><%= @user.introduce %></p>
  </div>
  <div class= "col-lg-2 offset-md-5">
      <span><%= render 'relationships/follow_button', user: @user %></span>
  </div>
</div>


<div class= "container">
  <div class="row pt-3">
    <div class="col-sm-12">
        <ul class="nav nav-tabs nav-justified mb-4">
          <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">IDEAS <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link  <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
        </ul>
    <%= render 'posts/posts', posts: @favorites %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1 class="pt-4">新規登録</h1>
</div>
<div class="container pb-5">
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（もう1度入力してください）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <p>
        <%= f.check_box :agreement, :as => :boolean, checked:false %>
        <small><%= link_to '利用規約', protocol_path %>と<%= link_to 'プライバシーポリシー', privacy_path %>に同意する</small>
      </p>

      <%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row pt-3">
    <aside class="col-md-4">
      <% if @user.image? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg" %>
      <% end %>
    </aside>
  <div class="col-lg-8 ">
    <h3><%= @user.name %></h3>
    <h6>性別：<%= @user.sex %></h6>
    <h6>年齢：<%= @user.age %>代</h6>
    <h6>自己紹介</h6>
        <p><%= @user.introduce %></p>
    
  </div>
  <div class= "col-lg-2 offset-md-5">
      <span><%= render 'relationships/follow_button', user: @user %></span>
  </div>
</div>


<div class= "container">
  <div class="row pt-3">
    <div class="col-sm-12">
        <ul class="nav nav-tabs nav-justified mb-4">
          <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">IDEAS <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link  <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
        </ul>
    <%= render 'posts/posts', posts: @posts %>
    </div>
  </div>
</div>