config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'privacy', to: "toppages#privacy"
  get 'protocol', to: "toppages#protocol"
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  resources :posts, only: [:new, :create, :edit, :show, :update, :destroy] do 
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 255 }
  
  has_many :favorites, dependent: :destroy
  has_many :fav_users, through: :favorites, source: :user,dependent: :destroy
  
  has_many :comments,dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'アイデアを投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'アイデアの投稿に失敗しました。'
      render 'toppages/index'
    end  
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    #@comment = @post.comments.build
   
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
    flash[:success] = 'アイデアが編集されました'
    redirect_to @post
    else
    flash.now[:danger] = 'アイデアが編集されませんでした'
    render :new
    end
  end
  

  def destroy
    @post.destroy
    flash[:success] = 'アイデアを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_posts.html.erb
<ul class="container list-unstyled">
  <% posts.each do |post| %>
    <li class="media pt-4 mb-3 border-bottom">
      <% if post.user.image? %>
        <%= image_tag post.user.image.thumb130.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg", :size => '130x130' %>
      <% end %>
      <div class="media-body pl-3">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">投稿日時 <%= post.created_at %></span>
        </div>
        <div>
          <p><%= post.title %></p>
          <p><%= post.content %></p>
        </div>
        <div class="pb-2">
          <ul class="list-inline">
            <li class="list-inline-item">
              <% if current_user.favorite?(post) %>
                <%= form_with(model: current_user.favorites.find_by(post_id: post.id), local: true, method: :delete) do |f| %>
                  <%= hidden_field_tag :post_id, post.id %>
                  <%= f.submit 'いいね！解除', class: 'btn btn-warning btn-sm'%>
                <% end %>
              <% else %>
                <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
                  <%= hidden_field_tag :post_id, post.id %>
                  <%= f.submit 'いいね！' , class: 'btn btn-primary btn-sm'%>
                <% end %>
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to '詳細',post_path(post), class: 'btn btn-success btn-sm' %>
            </li>
            <li class="list-inline-item">
              <% if current_user == post.user %>
                <%= link_to "削除", post, method: :delete, data: { confirm: "本当に削除してもよろしいですか?" }, class: 'btn btn-danger btn-sm' %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </li>
　 <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/edit.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">

    <h3><%= @post.user.name %> さんの編集ページ</h1>

    <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

    <div class="form-group">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content, 'アイデア' %>
      <%= f.text_area :content, class: 'form-control', rows: 7 %>
    </div>
      
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row pt-4">
  <div class="container">
    <div class="col-md-8 offset-md-2">
      <h2>IDEA投稿 <i class="fas fa-share"></i></h2>
    
      <%= form_with(model: @post, local: true) do |f| %>
        <div class="form-group">
          <h5>タイトル</h5>
          <%= f.text_field :title, class: 'form-control' %>
          
          <h5>IDEA</h5>
          <%= f.text_area :content, class: 'form-control', rows: 7 %>
        </div>
        <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<ul class="container list-unstyled">
  <li class="media pt-4 pb-3 border-bottom">
    <% if @post.user.image? %>
        <%= image_tag @post.user.image.thumb130.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg",:size => '130x130' %>
      <% end %>
  <div class="media-body pl-3">
    <div>
      <%= link_to @post.user.name, user_path(@post.user) %> <span class="text-muted">投稿日時 <%= @post.created_at %></span>
    </div>
    <div>
      <p><%= @post.title %></p>
      <p><%= @post.content %></p>
    </div>
    <ul class="list-inline">
      <li class="list-inline-item">
        <% if current_user.favorite?(@post) %>
          <%= form_with(model: current_user.favorites.find_by(post_id: @post.id), local: true, method: :delete) do |f| %>
            <%= hidden_field_tag :post_id, @post.id %>
            <%= f.submit 'いいね！解除', class: 'btn btn-danger btn-sm'%>
          <% end %>
        <% else %>
          <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
            <%= hidden_field_tag :post_id, @post.id %>
            <%= f.submit 'いいね！' , class: 'btn btn-primary btn-sm'%>
          <% end %>
        <% end %>
      </li>
      <li class="list-inline-item">
        <% if current_user == @post.user %>
          <%= link_to "編集",edit_post_path, class: 'btn btn-success btn-sm'%>
        <% end %>
      </li>
      <li class="list-inline-item">
        <% if current_user == @post.user %>
          <%= link_to "削除", @post, method: :delete, data: { confirm: "本当に削除してもよろしいですか?" }, class: 'btn btn-danger btn-sm' %>
        <% end %>
      </li>
    </ul>
  </div>
  </li>
</ul>
<div class="container pb-5">
  <h1>コメント一覧</h1>
  <% @comments.each do |c| %>
     <li class="media pt-4 pb-3 border-bottom">
       <% if c.post.user.image? %>
        <%= image_tag c.post.user.image.thumb130.url %>
      <% else %>
        <%= image_tag "/assets/icon.jpg", :size => '130x130' %>
      <% end %>
       <div class="media-body pl-3 pb-5">
        <div>
          <%= link_to c.user.name, user_path(c.user) %> <span class="text-muted">投稿日時 <%= c.created_at %></span>
        </div>
        <div>
          <%= c.content %>
        </div>
     </li>
  <% end %>
  <%= form_with(model: [@post, @post.comments.build], local: true) do |f| %>
   <%= f.text_area :content, class: "form-control", rows: 3 %>
   <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
   <i class="far fa-comments"></i> コメントする
   <% end %>
  <% end %>
</div>
      
      

  